{% set name = "hep_ml" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0438f4d0e9f3ca95e020484774255c03c34f422df740a238ae2dbee1f76861b8

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
  run:
    - numpy >=1.9
    - pandas >=0.14.0
    - python
    - scikit-learn >=0.19
    - scipy >=0.15.0
    - six
    - theano >=1.0.2

test:
  imports:
    - hep_ml
    - hep_ml.experiments

about:
  home: https://github.com/arogozhnikov/hep_ml
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Machine Learning for High Energy Physics
  doc_url: https://github.com/arogozhnikov/hep_ml
  dev_url: https://github.com/arogozhnikov/hep_ml

extra:
  recipe-maintainers:
    - chrisburr
