travis:
  secure:
    BINSTAR_TOKEN: xrvbPwg6Rkc93D7OihBa2DMLTrvlRb8VRCFu5xb+ddinn4LM5dE8HLNoC70Oc+N819dhEioEZxmq6+EMYdXIk2PeGHlHMyxuCkRgsmlcmZaNgll5iYf9iAMgrdNzB6L+roQBvJoNg7v9wlK5I4/9edwhlgtbs2NoVpsieeS5NoczqPHJSzcJGfSOo5UdjmMLi3o1cP8bwtPzTu+6cSuEaHynuNJEhhBk83Om70Yh22FyUM6Td0sbiXbwRs43wqoKOLmjOfaltAbiUeK5alEJG3i8/PKpcbsvn+JW7+84AJCeZj861S+WQBXJtyqp3a9ZTkNNzwXy7RXlNSGTmalxQ7IyLJueV+NsEpra+nVbI7kTOZul9W60Em77mtGnc/Vpt6ciWpUISJF8Q9vKEAhiyfI8EQnS3GJPDM89UF8AwI2291cSqxsSNcq0wRRsbXAxCYq2Jh5xfWomgRVSuBRWBr0fgFilziKdfuaAOba5TVVHyd6mkyyqhnUhf/dhRk29FyE0dacpCgaSDyxRlODEsIR57miQzjsyIbxTMKiqVhA2WUmjnNkziAoqhqEpLfA4yObJnYqUgfdGHYFcj7ifSnPe/7yu1NLrWrsJc22DbeYa5y3ATboYiQU1F630Sl0Y5WhDn5BvD+iIaSSxNh9O5b5SVJeePZY4zSd0uGnhAkQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
