travis:
  secure:
    BINSTAR_TOKEN: tuvscMkrnrNF5TNP4n6fx7U1cxlNq4OI+zMnk/IBxxprB6lqOYytfajjDtESQ9l2S8wlMXiNWLDi4bHMdOAck6U9d1kFyF9v5gimdlYnPNBb4aIP+rcvXBqhJjXdYafqu6L1NHOyotFiNhJJG2g56xcH9H7nhecdVnpxmDu0cnSsb72MaSlnI55dB3iJvua4Qs5XHfVDycEjmt44IDhgR3ezPmtFbyrNvPgWlXWBo6S4CfgOBovHRQ+iEOS1FSVdk5Bii8SrCiyHmeVP6XLKdP3oy8npZz6GOmzeLj+g5EnWJSI2vODmyJnv6BJEAVlpXPK/v8KYKRKgLuVHp0la3QzZN+zW9o29ZP8ofdqXKU2rIVuw3hcpYFSkloVEtgSVL6jPCs62zs9KoI0B5FNQDH6U8JzKgOEFDcyvSWUlQgwEO1NKra+r4FmICGhPvXAuX9UQYo/ibi6OtAVfueWJ8scRxRjlOcOwY9zZk6qULjuWIOFHQCdBQLctOli0s1QEImjTY3fZoWj1pcVrudDQv0kPZJO610yOY44AfpEEzK2JOq6c2DhHlwF1pbWh0pg//D/e7p0WJdr28d/a+Mrhu71tvGVZy0daC9xWuHOFzKMqjxxpER4we9deW6PL4zIf5WyWUl56BhxZ7VsoKkQ+K+uGfKcfEGCqTLBIhZzJs3s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
